#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Mar 08 08:34:17 CDT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=12
shaderPack=ComplementaryReimagined_r5.7.1.zip
